"""AEGIS AI — Generate Report MCP Tool
Synthesizes operational findings, analytics, and metrics into structured Markdown executive reports.
"""

from datetime import UTC, datetime
from typing import Any

from pydantic import BaseModel, Field

from backend.tools.base import BaseTool, ToolExecutionContext


class GenerateReportArgs(BaseModel):
    title: str = Field(..., description="Executive report title")
    summary: str = Field(..., description="Executive summary overview")
    key_findings: list[str] = Field(default_factory=list, description="Bulleted list of key operational findings")
    metrics: dict[str, Any] = Field(default_factory=dict, description="Key numerical metrics and KPIs to include")
    recommendations: list[str] = Field(default_factory=list, description="Actionable recommendations")


class GenerateReportTool(BaseTool):
    name = "generate_report"
    description = (
        "Compiles multi-source operational metrics, analytical findings, and recommendations "
        "into a publication-ready structured executive report in Markdown format."
    )
    category = "REPORTING"
    required_permission = "reports.create"
    args_schema = GenerateReportArgs

    async def execute(self, arguments: dict[str, Any], context: ToolExecutionContext) -> dict[str, Any]:
        args = self.args_schema(**arguments)
        now_str = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC")

        # Markdown Document Construction
        lines = [
            f"# {args.title}",
            f"*Generated by AEGIS AI on {now_str}*",
            "",
            "## 1. Executive Summary",
            args.summary,
            "",
        ]

        if args.metrics:
            lines.extend([
                "## 2. Operational Key Performance Indicators",
                "| Metric | Value |",
                "| :--- | :--- |",
            ])
            for k, v in args.metrics.items():
                lines.append(f"| **{k}** | `{v}` |")
            lines.append("")

        if args.key_findings:
            lines.extend([
                "## 3. Key Findings & Empirical Analysis",
            ])
            for idx, finding in enumerate(args.key_findings, 1):
                lines.append(f"{idx}. {finding}")
            lines.append("")

        if args.recommendations:
            lines.extend([
                "## 4. Strategic & Tactical Recommendations",
            ])
            for idx, rec in enumerate(args.recommendations, 1):
                lines.append(f"- **REC-{idx:02d}**: {rec}")
            lines.append("")

        lines.extend([
            "## 5. Governance & Audit Verification",
            f"- **Tenant Organization**: `{context.organization_id}`",
            f"- **Author / Initiator**: `{context.user_id}`",
            "- **Integrity Verification**: Verified by AEGIS AI Autonomous Supervisor",
            "",
        ])

        report_markdown = "\n".join(lines)

        return {
            "title": args.title,
            "generated_at": now_str,
            "char_count": len(report_markdown),
            "report_markdown": report_markdown,
        }
