"""AEGIS AI — Executive Report Schemas
Pydantic v2 schemas for multi-modal report creation, listing, and inspection.
"""

from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class ReportCreateRequest(BaseModel):
    """Payload to create and compile a new executive report."""

    title: str = Field(min_length=3, max_length=255, description="Executive report title")
    summary: str | None = Field(default=None, description="Executive summary overview")
    content_markdown: str = Field(min_length=10, description="Full report content in Markdown format")
    format: str = Field(default="PDF", description="Format: MARKDOWN or PDF")
    agent_run_id: str | None = Field(default=None, description="Linked AgentRun ID if generated by autonomous agent")
    charts_data: list[dict[str, Any]] | None = Field(default=None, description="Optional structured chart series")
    metrics_data: dict[str, Any] | None = Field(default=None, description="Key operational metrics KPI dictionary")


class ReportResponse(BaseModel):
    """Serialized report metadata and contents."""

    model_config = ConfigDict(from_attributes=True)

    id: str
    organization_id: str
    user_id: str
    agent_run_id: str | None = None
    title: str
    summary: str | None = None
    format: str
    content_markdown: str
    pdf_storage_path: str | None = None
    charts_data: list[dict[str, Any]] | None = None
    metrics_data: dict[str, Any] | None = None
    created_at: datetime
    updated_at: datetime


class ReportListItem(BaseModel):
    """Lightweight summary of a report for listing views."""

    model_config = ConfigDict(from_attributes=True)

    id: str
    organization_id: str
    user_id: str
    agent_run_id: str | None = None
    title: str
    summary: str | None = None
    format: str
    has_pdf: bool = False
    created_at: datetime


class ReportListResponse(BaseModel):
    """Paginated collection of reports."""

    reports: list[ReportResponse]
    total: int
